---
  - name: To install the kubectl 
    hosts: localhost
    connection: local
    tasks:
     - name: copy the kubernetes repo to the local server 
       copy:
         src: ./files/kubernetes.repo
         dest: ~/kubernetes.repo
         mode: '0664'

     - name: install kubectl 
       yum:
         name: kubectl
         state: latest


     - name: create .kube directory on the local host
       file:
         path: ~/.kube
         state: directory
         mode: 0755
 
     - name: Install helm 
       unarchive:
         src: https://get.helm.sh/helm-v3.11.3-linux-amd64.tar.gz
         dest: /usr/local/bin
         extra_opts: "--strip-components=1"
         owner: root
         group: root
         mode: 0755
         remote_src: true
       args:
         creates: /usr/local/bin/helm

       tags: 
         - helm 


  
