---
  - name: To install the kubectl 
    hosts: localhost
    connection: local
    become_user: root
    tasks:
     - name: copy the kubernetes repo to the local server 
       copy:
         src: ./files/kubernetes.repo
         dest: ~/kubectl.repo
         mode: '0664'

     - name: install kubectl 
       yum:
         name: kubectl
         state: latest

     - name: create .kube directory on the local host
       file:
         path: ~/.kube
         state: directory
         mode: 0755
      
      

       

