---
  - name: To install the kubectl 
    hosts: localhost
    connection: local
    tasks:
     - name: copy the kubernetes repo to the local server 
       copy:
         src: ./files/kubernetes.repo
         dest: ~/kubernetes.repo
         mode: '0664'

     - name: install kubectl 
       yum:
         name: kubectl
         state: latest


     - name: create .kube directory on the local host
       file:
         path: ~/.kube
         state: directory
         mode: 0755
       become: false
       delegate_to: localhost
       
     - name: copying the kubeconfig file to the local machine
       fetch: src=/etc/kubernetes/admin.conf dest=~/.kube/config  flat=yes
       delegate_to: k8-masternode.rps.local
