---
  - name: create kubernetes cluster master node setup
    hosts: k8s_master
    become: yes
    tasks:


      - name: initialize the cluster
        command: kubeadm init --apiversion-advertise-address="{{groups['k8s_master'][0]}}" --pod-network-cidr=192.168.0.0/16
        ignore_errors: True
    
      - name: remove the container
        file:
          path: /etc/containerd/config.toml
          state: absent

      - name: restart containerd
        systemd:
          name: containerd
          state: restarted

      - name: kubeadm reset
        shell: |
           kubeadm reset -f
      - name: restart kubelet
        systemd:
           name: kubelet
           state: restarted

      - name: echo 1
        shell:
          sysctl net.bridge.bridge-nf-call-iptables=1

      - name: initialize the cluster
        shell: kubeadm init
        args:
          chdir: /root
          creates: cluster_initialized.txt

      - name: create .kube directory
        file:
          path: /root/.kube
          state: directory
          mode: 0755

      - name: copies admin.conf to user's kube config
        copy:
          src: /etc/kubernetes/admin.conf
          dest: /root/.kube/config
          remote_src: yes
          owner: root
 
      - name: copying the kubeconfig file to the local machine
<<<<<<< HEAD
        fetch: src=/etc/kubernetes/admin.conf dest=~/.kube/config  flat=yes
        tags: kubectl
=======
        fetch: 
          src: /etc/kubernetes/admin.conf 
          dest: /tmp/config  
          flat: yes
          mode: 0777
          
      - name: copy /tmp/config to root
        copy:
          src: /tmp/config
          dest: /root/.kube/
        become: yes
        delegate_to: localhost
>>>>>>> 7ceabb18cdc3aa0d5994f5502a72e250213193c4

      - name: install Pod network
        shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml

      - name: Get the token for joining the worker nodes
        shell: kubeadm token create  --print-join-command
        register: kubernetes_join_command
     

      - name: Copy join command to local file
        copy: content="{{ kubernetes_join_command.stdout }}" dest="~/kubernetes_join_command" mode=0777
        become: false  
        delegate_to: localhost 

